### ISSUE TITLE
Runtime Error while evaluating the model

### ISSUE THREAD

**Issue by rohanakut** [vpulab/Semantic-Aware-Scene-Recognition#21]
I am getting the following error on running evaluation.py

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

This is the stack trace
Traceback (most recent call last):
  File "evaluation.py", line 300, in <module>
    val_top1, val_top2, val_top5, val_loss, val_ClassTPDic = evaluationDataLoader(val_loader, model, set='Validation')
  File "evaluation.py", line 110, in evaluationDataLoader
    prec1, prec2, prec5 = utils.accuracy(outputSceneLabel.data, sceneLabelGT, topk=(1, 2, 5))
  File "/content/Semantic-Aware-Scene-Recognition/Libs/Utils/utils.py", line 108, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

Could you please help me with this issue?

**Comment by alexlopezcifuentes** [comment]
Hi!

I have also encountered that error in my code and in others. It seems that something has changed in newer versions of PyTorch and view function is no longer usable in that situation.

I recommend you to use the PyTorch version specified in the requirements Section or change that line for: 

`correct_k = correct[:k].reshape(-1).float().sum(0)`

I will update the code ASAP to fix that bug.
